# Databricks notebook source
# /// script
# [tool.databricks.environment]
# environment_version = "5"
# ///
# MAGIC %md
# MAGIC # Step 2 — Bronze Parsing: JSON → Normalised Tables (Dynamic, Multi-Domain)
# MAGIC **Pipeline:** Dynamic MDM Platform | **Layer:** Bronze
# MAGIC
# MAGIC Reads from the generic `bronze.sland_mdm` landing table produced by Step 1
# MAGIC (which already tags every row with a content-detected `domain_code` —
# MAGIC `RETAIL` / `HEALTHCARE`) and parses the raw JSON into normalised Bronze
# MAGIC tables that both domains write into, side by side.
# MAGIC
# MAGIC ## Table Structure
# MAGIC
# MAGIC | Table | PK | FK | Source Nodes Merged |
# MAGIC |---|---|---|---|
# MAGIC | `bronze.sourceconsumer` | `src_id` (auto-increment) | `sln_id` → sland_mdm.sln_id | Header + Consumer/Patient + SourceSystem + BestRecord + PersonalData |
# MAGIC | `bronze.sourcemedia` | `srme_id` (auto-increment) | `srme_src_id` → sourceconsumer.src_id | ContactInformation → EMediaList |
# MAGIC | `bronze.sourcephone` | `srph_id` (auto-increment) | `srph_src_id` → sourceconsumer.src_id | ContactInformation → PhoneList |
# MAGIC | `bronze.sourceaddress` | `srad_id` (auto-increment) | `srad_src_id` → sourceconsumer.src_id | ContactInformation → AddressList |
# MAGIC | `bronze.sourceoptin` | `srop_id` (auto-increment) | `srop_src_id` → sourceconsumer.src_id | OptInList |
# MAGIC
# MAGIC ## Key design points
# MAGIC - **`src_id` is a real auto-increment PK** (`GENERATED BY DEFAULT AS IDENTITY`,
# MAGIC   not `ALWAYS`) — this lets us *compute* the next block of IDs in Python
# MAGIC   before writing, so the same `src_id` values are known and can be reused
# MAGIC   as the FK when building the child (media/phone/address/optin) DataFrames
# MAGIC   in the same run, without a second read-back from Delta.
# MAGIC - **`sln_id`** (the landing-table row id) is kept as a plain traceability
# MAGIC   column on `sourceconsumer`, separate from the `src_id` PK.
# MAGIC - **Domain-aware parsing**: `bronze.domain_config` tells us the JSON root
# MAGIC   entity per domain (`Consumer` vs `Patient`); a small in-notebook
# MAGIC   field-name map handles the handful of fields named differently between
# MAGIC   domains (e.g. `AssignedPersonnelCode` vs `AssignedPhysicianCode`). This
# MAGIC   map is the one place to edit if a new domain's field names differ — a
# MAGIC   natural next step is to move it into a `bronze.field_mapping_config`
# MAGIC   table, same pattern as `domain_config`.
# MAGIC - **Auto schema evolution**: schema is inferred fresh from each domain's
# MAGIC   batch via `schema_of_json`, and every write uses `mergeSchema = true`,
# MAGIC   so new JSON fields appear as new columns automatically.
# MAGIC - **List-or-single-object safe**: `ContactInformation` sub-nodes
# MAGIC   (EMedia/Phone/Address) are sometimes a single JSON object and sometimes
# MAGIC   an array depending on the payload. A small helper detects which, and
# MAGIC   wraps single objects in an array before exploding, so both shapes
# MAGIC   produce exactly one row per contact point.
# MAGIC - **Latest batch is resolved per domain from `sland_mdm` itself**
# MAGIC   (content-detected `domain_code`), joined to `batch_control` for
# MAGIC   `COMPLETED` status — not from the folder-implied domain — so it stays
# MAGIC   correct even if a file was ever landed in the "wrong" domain's folder.

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2.1 — Use Catalog / Bronze Schema

# COMMAND ----------

# MAGIC %sql
# MAGIC USE CATALOG MDM_Platform;
# MAGIC
# MAGIC CREATE SCHEMA IF NOT EXISTS bronze
# MAGIC COMMENT 'Bronze / raw-landing + parsed layer for Dynamic MDM Platform';

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2.2 — DDL: bronze.sourceconsumer
# MAGIC Merges Header + root entity (Consumer/Patient) + SourceSystem + BestRecord + PersonalData.
# MAGIC `src_id` is `GENERATED BY DEFAULT AS IDENTITY` so we can supply explicit,
# MAGIC pre-computed values from Python while still keeping identity semantics.

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS bronze.sourceconsumer (
# MAGIC     src_id                      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
# MAGIC     sln_id                      BIGINT      NOT NULL,   -- FK → bronze.sland_mdm.sln_id (traceability)
# MAGIC     batch_id                    BIGINT      NOT NULL,
# MAGIC     domain_code                 STRING,                 -- RETAIL | HEALTHCARE (content-detected)
# MAGIC     source_code                 STRING,                 -- IDN | HCR
# MAGIC     root_entity_name            STRING,                 -- Consumer | Patient
# MAGIC     record_uuid                 STRING,
# MAGIC     -- ── Header node ──────────────────────────────────────────────────────
# MAGIC     action                      STRING,                 -- Header.@Action
# MAGIC     document_timestamp          TIMESTAMP,
# MAGIC     document_uuid               STRING,
# MAGIC     -- ── SourceSystem node ────────────────────────────────────────────────
# MAGIC     source_system_code          STRING,                 -- SourceSystem.@Code
# MAGIC     source_timestamp            TIMESTAMP,
# MAGIC     affiliate_code              STRING,
# MAGIC     market_code                 STRING,
# MAGIC     division_code               STRING,
# MAGIC     brand_code                  STRING,
# MAGIC     source_entity_id            STRING,                 -- ConsumerId | PatientId
# MAGIC     -- ── BestRecord node ──────────────────────────────────────────────────
# MAGIC     universal_key               STRING,
# MAGIC     -- ── PersonalData node (common across domains) ───────────────────────
# MAGIC     salutation                  STRING,
# MAGIC     local_first_name            STRING,
# MAGIC     local_last_name             STRING,
# MAGIC     local_full_name             STRING,
# MAGIC     birth_day                   INT,
# MAGIC     birth_month                 INT,
# MAGIC     birth_year                  INT,
# MAGIC     reg_date                    TIMESTAMP,
# MAGIC     reg_touchpoint_code         STRING,
# MAGIC     preferred_touchpoint_code   STRING,
# MAGIC     assigned_staff_code         STRING,                 -- AssignedPersonnelCode | AssignedPhysicianCode
# MAGIC     written_language_code       STRING,
# MAGIC     country_code_iso3           STRING,                 -- ConsumerCountryCode_ISO3 | PatientCountryCode_ISO3
# MAGIC     gender_code                 STRING,
# MAGIC     active_flag                 BOOLEAN,
# MAGIC     first_engagement_date       TIMESTAMP,               -- FirstPurchaseDate | FirstVisitDate
# MAGIC     -- ── PersonalData node (healthcare-only; null for other domains) ─────
# MAGIC     marital_status_code         STRING,
# MAGIC     nationality_code_iso3       STRING,
# MAGIC     patient_category_code       STRING,
# MAGIC     -- ── Audit ────────────────────────────────────────────────────────────
# MAGIC     creation_dt                 TIMESTAMP,
# MAGIC     updation_dt                 TIMESTAMP
# MAGIC )
# MAGIC USING DELTA
# MAGIC TBLPROPERTIES ('delta.enableChangeDataFeed' = 'true')
# MAGIC COMMENT 'Bronze root entity — Header + Consumer/Patient + SourceSystem + BestRecord + PersonalData merged, all domains';

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2.3 — DDL: bronze.sourcemedia

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS bronze.sourcemedia (
# MAGIC     srme_id             BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
# MAGIC     srme_src_id         BIGINT      NOT NULL,   -- FK → bronze.sourceconsumer.src_id
# MAGIC     type_code           STRING,                 -- EMedia.@TypeCode
# MAGIC     source_timestamp    TIMESTAMP,
# MAGIC     email_address       STRING,
# MAGIC     is_primary          BOOLEAN,
# MAGIC     creation_dt         TIMESTAMP,
# MAGIC     updation_dt         TIMESTAMP
# MAGIC )
# MAGIC USING DELTA
# MAGIC COMMENT 'Bronze email contacts — srme_id PK, srme_src_id FK to sourceconsumer.src_id';

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2.4 — DDL: bronze.sourcephone

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS bronze.sourcephone (
# MAGIC     srph_id             BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
# MAGIC     srph_src_id         BIGINT      NOT NULL,   -- FK → bronze.sourceconsumer.src_id
# MAGIC     type_code           STRING,                 -- Phone.@TypeCode
# MAGIC     source_timestamp    TIMESTAMP,
# MAGIC     phone_number        STRING,
# MAGIC     is_primary          BOOLEAN,
# MAGIC     creation_dt         TIMESTAMP,
# MAGIC     updation_dt         TIMESTAMP
# MAGIC )
# MAGIC USING DELTA
# MAGIC COMMENT 'Bronze phone contacts — srph_id PK, srph_src_id FK to sourceconsumer.src_id';

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2.5 — DDL: bronze.sourceaddress

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS bronze.sourceaddress (
# MAGIC     srad_id                     BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
# MAGIC     srad_src_id                 BIGINT      NOT NULL,   -- FK → bronze.sourceconsumer.src_id
# MAGIC     type_code                   STRING,
# MAGIC     source_timestamp            TIMESTAMP,
# MAGIC     address1                    STRING,
# MAGIC     address2                    STRING,
# MAGIC     address3                    STRING,
# MAGIC     city_description_local      STRING,
# MAGIC     province_description_local  STRING,
# MAGIC     country_code_iso3           STRING,
# MAGIC     postal_code                 STRING,
# MAGIC     is_primary                  BOOLEAN,
# MAGIC     creation_dt                 TIMESTAMP,
# MAGIC     updation_dt                 TIMESTAMP
# MAGIC )
# MAGIC USING DELTA
# MAGIC COMMENT 'Bronze address contacts — srad_id PK, srad_src_id FK to sourceconsumer.src_id';

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2.6 — DDL: bronze.sourceoptin

# COMMAND ----------

# MAGIC %sql 
# MAGIC use catalog mdm_platform;
# MAGIC select * from bronze.sourceoptin;
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS bronze.sourceoptin (
# MAGIC     srop_id                     BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
# MAGIC     srop_src_id                 BIGINT      NOT NULL,   -- FK → bronze.sourceconsumer.src_id
# MAGIC     communication_channel_code  STRING,
# MAGIC     opt_in_flag                 BOOLEAN,
# MAGIC     opt_in_timestamp            TIMESTAMP,
# MAGIC     creation_dt                 TIMESTAMP,
# MAGIC     updation_dt                 TIMESTAMP
# MAGIC )
# MAGIC USING DELTA
# MAGIC COMMENT 'Bronze opt-in preferences — srop_id PK, srop_src_id FK to sourceconsumer.src_id';

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2.7 — DDL: bronze.parse_control
# MAGIC Tracks which `(domain_code, batch_id)` combinations have already been
# MAGIC parsed into `sourceconsumer` + child tables. This is what makes Step 2
# MAGIC idempotent: re-running the notebook against a batch that's already been
# MAGIC parsed processes **0 records** for that domain, instead of appending
# MAGIC duplicate rows. A new run only picks up domains whose latest completed
# MAGIC landing batch_id isn't yet marked `COMPLETED` here.

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS bronze.parse_control (
# MAGIC     parse_id      BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
# MAGIC     domain_code   STRING      NOT NULL,
# MAGIC     batch_id      BIGINT      NOT NULL,
# MAGIC     status        STRING,                 -- STARTED | COMPLETED | FAILED
# MAGIC     record_count  BIGINT,
# MAGIC     creation_dt   TIMESTAMP,
# MAGIC     updation_dt   TIMESTAMP
# MAGIC )
# MAGIC USING DELTA
# MAGIC COMMENT 'Tracks which (domain_code, batch_id) combos have been parsed into Bronze normalized tables — makes Step 2 idempotent';

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2.8 — Config: Domain-Specific Field Name Map
# MAGIC The handful of fields that are named differently between domains.
# MAGIC Add a row here (or promote this to a `bronze.field_mapping_config` table)
# MAGIC whenever a new domain uses different field names for these concepts.

# COMMAND ----------

# Maps generic column concept -> the actual JSON field name, per domain.
FIELD_NAME_MAP = {
    "RETAIL": {
        "entity_id_field":       "ConsumerId",
        "assigned_staff_field":  "AssignedPersonnelCode",
        "country_code_field":    "ConsumerCountryCode_ISO3",
        "first_engagement_field": "FirstPurchaseDate",
    },
    "HEALTHCARE": {
        "entity_id_field":       "PatientId",
        "assigned_staff_field":  "AssignedPhysicianCode",
        "country_code_field":    "PatientCountryCode_ISO3",
        "first_engagement_field": "FirstVisitDate",
    },
}

print(">>> Field name map loaded for domains:", list(FIELD_NAME_MAP.keys()))

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2.9 — Resolve Latest Completed Batch, Per Domain — Skip if Already Parsed
# MAGIC For each domain, find the latest `COMPLETED` landing batch (from
# MAGIC `sland_mdm` + `batch_control`, as before), then check `parse_control`:
# MAGIC - If that exact `(domain_code, batch_id)` already has a `COMPLETED` parse
# MAGIC   record → **skip** (0 records processed on this run).
# MAGIC - Otherwise → this batch is new (or previously `FAILED`) and gets parsed.
# MAGIC
# MAGIC This is the idempotency gate: running the notebook twice in a row against
# MAGIC the same Step 1 batch does real work only once.

# COMMAND ----------

from pyspark.sql import functions as F, types as T
from pyspark.sql.types import ArrayType

latest_landing_batches = spark.sql("""
    SELECT s.domain_code, MAX(s.batch_id) AS batch_id
    FROM   bronze.sland_mdm s
    JOIN   bronze.batch_control bc ON bc.batch_id = s.batch_id
    WHERE  bc.status = 'COMPLETED'
    GROUP  BY s.domain_code
""").collect()

already_parsed = {
    (r["domain_code"], r["batch_id"])
    for r in spark.sql("""
        SELECT domain_code, batch_id
        FROM   bronze.parse_control
        WHERE  status = 'COMPLETED'
    """).collect()
}

latest_batches = []
print(">>> Latest completed landing batch per domain:")
for row in latest_landing_batches:
    domain_code, batch_id = row["domain_code"], row["batch_id"]
    if (domain_code, batch_id) in already_parsed:
        print(f"    {domain_code}: batch_id = {batch_id} — already parsed, SKIPPING (0 records)")
    else:
        print(f"    {domain_code}: batch_id = {batch_id} — new, will parse")
        latest_batches.append(row)

if not latest_batches:
    print("\n>>> Nothing new to parse for any domain. Step 2 exiting — 0 records processed.")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2.10 — Helper: Safe Explode (handles single-object OR array JSON nodes)

# COMMAND ----------

def safe_explode(df, fk_col, node_col, node_alias):
    """
    Explodes a nested JSON node that may be either a single struct or an
    array of structs, depending on the payload — always yields one row
    per contact point either way, with the FK column preserved alongside.
    NULL nodes yield one null-valued row (via explode_outer), so parent
    rows are never dropped.
    """
    dtype = df.schema[node_col].dataType
    node_expr = F.col(node_col) if isinstance(dtype, ArrayType) else F.array(F.col(node_col))
    return df.select(fk_col, F.explode_outer(node_expr).alias(node_alias))

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2.11 — Parse Each New Domain Batch and Write All 5 Tables

# COMMAND ----------

def _parse_domain_batch(row):

    domain_code = row["domain_code"]
    batch_id    = row["batch_id"]

    if domain_code not in FIELD_NAME_MAP:
        print(f">>> WARNING: no FIELD_NAME_MAP entry for domain '{domain_code}' — skipping.")
        return 0

    fmap = FIELD_NAME_MAP[domain_code]

    print(f"\n=== Parsing domain: {domain_code} | batch_id: {batch_id} ===")

    # ---- Open parse_control record for this (domain, batch) -----------------
    spark.sql(f"""
        INSERT INTO bronze.parse_control
            (domain_code, batch_id, status, record_count, creation_dt, updation_dt)
        VALUES
            ('{domain_code}', {batch_id}, 'STARTED', 0,
             current_timestamp(), current_timestamp())
    """)

    # ---- Pull raw payloads for this domain's latest batch -------------------
    df_raw = spark.sql(f"""
        SELECT sln_id, batch_id, domain_code, source_code, root_entity_name, raw_payload, record_uuid
        FROM   bronze.sland_mdm
        WHERE  domain_code = '{domain_code}'
        AND    batch_id    = {batch_id}
    """)

    root = df_raw.select("root_entity_name").first()["root_entity_name"]

    # ---- Infer JSON schema from this domain's batch and parse ----------------
    # (auto schema evolution: whatever fields exist in this run's payloads
    # become the columns — no manual DDL edits needed for new fields)
    schema_string = (
        df_raw.select(F.schema_of_json(F.col("raw_payload")).alias("s"))
              .first()["s"]
    )
    json_schema = T._parse_datatype_string(schema_string)
    df_parsed = df_raw.withColumn("p", F.from_json(F.col("raw_payload"), json_schema))

    record_count = df_parsed.count()
    print(f">>> Payloads parsed: {record_count}")

    root_path = f"p.{root}"

    # ---- Compute next block of src_id values in Python -----------------------
    # (so the same values can be reused as FK when building child DataFrames)
    next_src_id = (
        spark.sql("SELECT COALESCE(MAX(src_id), 0) AS max_id FROM bronze.sourceconsumer")
             .collect()[0]["max_id"]
    ) + 1

    from pyspark.sql.window import Window
    w = Window.orderBy("sln_id")

    df_parsed = df_parsed.withColumn(
        "src_id",
        (F.row_number().over(w) + F.lit(next_src_id) - 1).cast("bigint")
    )

    # ================================================================
    # 2.10a — bronze.sourceconsumer
    # ================================================================
    df_sourceconsumer = df_parsed.select(
        F.col("src_id"),
        F.col("sln_id"),
        F.col("batch_id").cast("bigint"),
        F.col("domain_code"),
        F.col("source_code"),
        F.col("root_entity_name"),
        F.col("record_uuid"),

        # ── Header node ──────────────────────────────────────────────
        F.upper(F.trim(F.col("p.Header.`@Action`"))).alias("action"),
        F.to_timestamp(F.col("p.Header.DocumentTimestamp")).alias("document_timestamp"),
        F.col("p.Header.DocumentUUID").alias("document_uuid"),

        # ── SourceSystem node ────────────────────────────────────────
        F.col(f"{root_path}.SourceSystem.`@Code`").alias("source_system_code"),
        F.to_timestamp(F.col(f"{root_path}.SourceSystem.SourceTimestamp")).alias("source_timestamp"),
        F.col(f"{root_path}.SourceSystem.AffiliateCode").alias("affiliate_code"),
        F.col(f"{root_path}.SourceSystem.MarketCode").alias("market_code"),
        F.col(f"{root_path}.SourceSystem.DivisionCode").alias("division_code"),
        F.col(f"{root_path}.SourceSystem.BrandCode").alias("brand_code"),
        F.col(f"{root_path}.SourceSystem.{fmap['entity_id_field']}").alias("source_entity_id"),

        # ── BestRecord node ──────────────────────────────────────────
        F.col(f"{root_path}.BestRecord.UniversalKey").alias("universal_key"),

        # ── PersonalData node (common) ───────────────────────────────
        F.col(f"{root_path}.PersonalData.Salutation").alias("salutation"),
        F.col(f"{root_path}.PersonalData.LocalFirstName").alias("local_first_name"),
        F.col(f"{root_path}.PersonalData.LocalLastName").alias("local_last_name"),
        F.col(f"{root_path}.PersonalData.LocalFullName").alias("local_full_name"),
        F.col(f"{root_path}.PersonalData.BirthDay").cast("int").alias("birth_day"),
        F.col(f"{root_path}.PersonalData.BirthMonth").cast("int").alias("birth_month"),
        F.col(f"{root_path}.PersonalData.BirthYear").cast("int").alias("birth_year"),
        F.to_timestamp(F.col(f"{root_path}.PersonalData.RegDate")).alias("reg_date"),
        F.col(f"{root_path}.PersonalData.RegTouchPointCode").alias("reg_touchpoint_code"),
        F.col(f"{root_path}.PersonalData.PreferredTouchPointCode").alias("preferred_touchpoint_code"),
        F.col(f"{root_path}.PersonalData.{fmap['assigned_staff_field']}").alias("assigned_staff_code"),
        F.col(f"{root_path}.PersonalData.WrittenLanguageCode").alias("written_language_code"),
        F.col(f"{root_path}.PersonalData.{fmap['country_code_field']}").alias("country_code_iso3"),
        F.col(f"{root_path}.PersonalData.GenderCode").alias("gender_code"),
        F.col(f"{root_path}.PersonalData.ActiveFlag").cast("boolean").alias("active_flag"),
        F.to_timestamp(F.col(f"{root_path}.PersonalData.{fmap['first_engagement_field']}")).alias("first_engagement_date"),

        # ── PersonalData node (healthcare-only; NULL for domains without them) ──
        F.col(f"{root_path}.PersonalData.MaritalStatusCode").alias("marital_status_code")
            if domain_code == "HEALTHCARE" else F.lit(None).cast("string").alias("marital_status_code"),
        F.col(f"{root_path}.PersonalData.NationalityCode_ISO3").alias("nationality_code_iso3")
            if domain_code == "HEALTHCARE" else F.lit(None).cast("string").alias("nationality_code_iso3"),
        F.col(f"{root_path}.PersonalData.PatientCategoryCode").alias("patient_category_code")
            if domain_code == "HEALTHCARE" else F.lit(None).cast("string").alias("patient_category_code"),

        # ── Audit ─────────────────────────────────────────────────────
        F.current_timestamp().alias("creation_dt"),
        F.current_timestamp().alias("updation_dt"),
    )

    (df_sourceconsumer
     .write
     .format("delta")
     .mode("append")
     .option("mergeSchema", "true")
     .saveAsTable("bronze.sourceconsumer"))

    print(f">>> bronze.sourceconsumer — {df_sourceconsumer.count()} rows written "
          f"(src_id {next_src_id} .. {next_src_id + record_count - 1})")

    _final_count = df_sourceconsumer.count()


    # ================================================================
    # 2.10b — bronze.sourcemedia  (ContactInformation.EMediaList.EMedia)
    # ================================================================
    df_media_base = df_parsed.select(
        F.col("src_id").alias("srme_src_id"),
        F.col(f"{root_path}.ContactInformation.EMediaList.EMedia").alias("_node")
    )
    df_media_exploded = safe_explode(df_media_base, "srme_src_id", "_node", "em")

    df_sourcemedia = df_media_exploded.select(
        F.col("srme_src_id"),
        F.col("em.`@TypeCode`").alias("type_code"),
        F.to_timestamp(F.col("em.SourceTimestamp")).alias("source_timestamp"),
        F.col("em.Address").alias("email_address"),
        F.when(F.col("em.Primary").cast("string").isin("true", "1", "yes"), F.lit(True))
         .otherwise(F.lit(False)).alias("is_primary"),
        F.current_timestamp().alias("creation_dt"),
        F.current_timestamp().alias("updation_dt"),
    )

    (df_sourcemedia
     .write.format("delta").mode("append")
     .option("mergeSchema", "true")
     .saveAsTable("bronze.sourcemedia"))

    print(f">>> bronze.sourcemedia — {df_sourcemedia.count()} rows written")

    # ================================================================
    # 2.10c — bronze.sourcephone  (ContactInformation.PhoneList.Phone)
    # ================================================================
    df_phone_base = df_parsed.select(
        F.col("src_id").alias("srph_src_id"),
        F.col(f"{root_path}.ContactInformation.PhoneList.Phone").alias("_node")
    )
    df_phone_exploded = safe_explode(df_phone_base, "srph_src_id", "_node", "ph")

    df_sourcephone = df_phone_exploded.select(
        F.col("srph_src_id"),
        F.col("ph.`@TypeCode`").alias("type_code"),
        F.to_timestamp(F.col("ph.SourceTimestamp")).alias("source_timestamp"),
        F.regexp_replace(F.trim(F.col("ph.PhoneNumber")), r"[\s\-\(\)]", "").alias("phone_number"),
        F.when(F.col("ph.Primary").cast("string").isin("true", "1", "yes"), F.lit(True))
         .otherwise(F.lit(False)).alias("is_primary"),
        F.current_timestamp().alias("creation_dt"),
        F.current_timestamp().alias("updation_dt"),
    )

    (df_sourcephone
     .write.format("delta").mode("append")
     .option("mergeSchema", "true")
     .saveAsTable("bronze.sourcephone"))

    print(f">>> bronze.sourcephone — {df_sourcephone.count()} rows written")

    # ================================================================
    # 2.10d — bronze.sourceaddress  (ContactInformation.AddressList.Address)
    # ================================================================
    df_addr_base = df_parsed.select(
        F.col("src_id").alias("srad_src_id"),
        F.col(f"{root_path}.ContactInformation.AddressList.Address").alias("_node")
    )
    df_addr_exploded = safe_explode(df_addr_base, "srad_src_id", "_node", "ad")

    df_sourceaddress = df_addr_exploded.select(
        F.col("srad_src_id"),
        F.col("ad.`@TypeCode`").alias("type_code"),
        F.to_timestamp(F.col("ad.SourceTimestamp")).alias("source_timestamp"),
        F.col("ad.Address1").alias("address1"),
        F.col("ad.Address2").alias("address2"),
        F.col("ad.Address3").alias("address3"),
        F.col("ad.CityDescription_local").alias("city_description_local"),
        F.col("ad.ProvinceDescription_local").alias("province_description_local"),
        F.col("ad.CountryCode_ISO3").alias("country_code_iso3"),
        F.col("ad.PostalCode").alias("postal_code"),
        F.when(F.col("ad.Primary").cast("string").isin("true", "1", "yes"), F.lit(True))
         .otherwise(F.lit(False)).alias("is_primary"),
        F.current_timestamp().alias("creation_dt"),
        F.current_timestamp().alias("updation_dt"),
    )

    (df_sourceaddress
     .write.format("delta").mode("append")
     .option("mergeSchema", "true")
     .saveAsTable("bronze.sourceaddress"))

    print(f">>> bronze.sourceaddress — {df_sourceaddress.count()} rows written")

    # ================================================================
    # 2.10e — bronze.sourceoptin  (OptInList.OptIn)
    # ================================================================
    df_optin_base = df_parsed.select(
        F.col("src_id").alias("srop_src_id"),
        F.col(f"{root_path}.OptInList.OptIn").alias("_node")
    )
    df_optin_exploded = safe_explode(df_optin_base, "srop_src_id", "_node", "oi")

    df_sourceoptin = df_optin_exploded.select(
        F.col("srop_src_id"),
        F.col("oi.CommunicationChannelCode").alias("communication_channel_code"),
        F.when(F.col("oi.OptInFlag").cast("string").isin("true", "1", "yes"), F.lit(True))
         .otherwise(F.lit(False)).alias("opt_in_flag"),
        F.to_timestamp(F.col("oi.OptInTimestamp")).alias("opt_in_timestamp"),
        F.current_timestamp().alias("creation_dt"),
        F.current_timestamp().alias("updation_dt"),
    )

    (df_sourceoptin
     .write.format("delta").mode("append")
     .option("mergeSchema", "true")
     .saveAsTable("bronze.sourceoptin"))

    print(f">>> bronze.sourceoptin — {df_sourceoptin.count()} rows written")


    return _final_count

# COMMAND ----------

for row in latest_batches:

    domain_code = row["domain_code"]
    batch_id    = row["batch_id"]

    try:
        final_record_count = _parse_domain_batch(row)

        spark.sql(f"""
            UPDATE bronze.parse_control
            SET    status       = 'COMPLETED',
                   record_count = {final_record_count},
                   updation_dt  = current_timestamp()
            WHERE  domain_code  = '{domain_code}'
            AND    batch_id     = {batch_id}
            AND    status       = 'STARTED'
        """)
        print(f">>> parse_control COMPLETED — {domain_code} batch_id={batch_id}, "
              f"{final_record_count} sourceconsumer rows written")

    except Exception as e:
        spark.sql(f"""
            UPDATE bronze.parse_control
            SET    status      = 'FAILED',
                   updation_dt = current_timestamp()
            WHERE  domain_code = '{domain_code}'
            AND    batch_id    = {batch_id}
            AND    status      = 'STARTED'
        """)
        raise RuntimeError(f"[{domain_code}] Step 2 parsing failed for batch_id={batch_id}: {e}")

print("\n>>> Step 2 complete — all Bronze parsed tables loaded for all domains.")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2.12 — QA: Parse Control History, Row Counts, FK Integrity, Preview

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Parse batch history — confirms idempotency: re-running Step 2 against
# MAGIC -- an already-COMPLETED (domain_code, batch_id) does not add a new row here
# MAGIC -- and processes 0 records upstream.
# MAGIC SELECT
# MAGIC     parse_id, domain_code, batch_id, status, record_count,
# MAGIC     creation_dt, updation_dt
# MAGIC FROM   bronze.parse_control
# MAGIC ORDER  BY parse_id DESC
# MAGIC LIMIT  20;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Row counts per table, split by domain where applicable
# MAGIC SELECT domain_code, COUNT(*) AS row_count, MAX(batch_id) AS latest_batch
# MAGIC FROM   bronze.sourceconsumer
# MAGIC GROUP  BY domain_code;

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT 'bronze.sourcemedia'  AS table_name, COUNT(*) AS row_count FROM bronze.sourcemedia
# MAGIC UNION ALL
# MAGIC SELECT 'bronze.sourcephone',   COUNT(*) FROM bronze.sourcephone
# MAGIC UNION ALL
# MAGIC SELECT 'bronze.sourceaddress', COUNT(*) FROM bronze.sourceaddress
# MAGIC UNION ALL
# MAGIC SELECT 'bronze.sourceoptin',   COUNT(*) FROM bronze.sourceoptin;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- FK integrity check: orphan child rows (must return 0 for all)
# MAGIC SELECT 'sourcemedia orphans'   AS check_name, COUNT(*) AS orphan_count
# MAGIC FROM   bronze.sourcemedia m
# MAGIC WHERE  NOT EXISTS (SELECT 1 FROM bronze.sourceconsumer c WHERE c.src_id = m.srme_src_id)
# MAGIC UNION ALL
# MAGIC SELECT 'sourcephone orphans',   COUNT(*)
# MAGIC FROM   bronze.sourcephone p
# MAGIC WHERE  NOT EXISTS (SELECT 1 FROM bronze.sourceconsumer c WHERE c.src_id = p.srph_src_id)
# MAGIC UNION ALL
# MAGIC SELECT 'sourceaddress orphans', COUNT(*)
# MAGIC FROM   bronze.sourceaddress a
# MAGIC WHERE  NOT EXISTS (SELECT 1 FROM bronze.sourceconsumer c WHERE c.src_id = a.srad_src_id)
# MAGIC UNION ALL
# MAGIC SELECT 'sourceoptin orphans',   COUNT(*)
# MAGIC FROM   bronze.sourceoptin o
# MAGIC WHERE  NOT EXISTS (SELECT 1 FROM bronze.sourceconsumer c WHERE c.src_id = o.srop_src_id);

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Preview: consumer/patient root joined with phone + address, across domains
# MAGIC SELECT
# MAGIC     c.src_id, c.domain_code, c.source_entity_id,
# MAGIC     c.local_first_name, c.local_last_name,
# MAGIC     c.assigned_staff_code, c.country_code_iso3, c.first_engagement_date,
# MAGIC     ph.phone_number, ph.is_primary AS phone_primary,
# MAGIC     ad.city_description_local, ad.province_description_local
# MAGIC FROM   bronze.sourceconsumer c
# MAGIC LEFT   JOIN bronze.sourcephone   ph ON ph.srph_src_id = c.src_id
# MAGIC LEFT   JOIN bronze.sourceaddress ad ON ad.srad_src_id = c.src_id
# MAGIC ORDER  BY c.domain_code, c.src_id;